[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]

[env]
ESP_LOG = "info"
